dist: trusty
sudo: required 
language: cpp

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      env: DOCKER_IMAGE=centos:7
    - os: linux
      env: DOCKER_IMAGE=fedora:25
    - os: linux
      env: DOCKER_IMAGE=fedora:24
    - os: linux
      env: DOCKER_IMAGE=fedora:23
    - os: linux
      env: DOCKER_IMAGE=debian:jessie
    - os: linux
      env: DOCKER_IMAGE=ubuntu:trusty
    - os: linux
      env: DOCKER_IMAGE=ubuntu:xenial
    - os: linux
      env: DOCKER_IMAGE=ubuntu:yakkety
    - os: linux
      env: DOCKER_IMAGE=ubuntu:zesty
#    - os: linux
#      env: DOCKER_IMAGE=ubuntu:xenial RUN_COVERAGE=1
    - os: osx
      env: OSX_BUILD=1 # used for README.md badges

script: ci/script.sh
