name: build and test
on: [pull_request]

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends libfuse-dev pkg-config clang-10 cmake
      - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} .. && make -j2
